version: '3.8'

services :
  redis:
    container_name: redis
    image: 'redis/redis-stack:latest'
    hostname: redis
    restart: unless-stopped
    environment:
      REDIS_ARGS: "--requirepass ${POSTGRES_PASSWORD}"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
      - "8001:8001"

  app:
    image: "craazzzyyfoxx/dude-duck-backend:latest"
    container_name: app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT} --loop uvloop
    ports:
      - "${PORT}:${PORT}"

  worker:
    image: "craazzzyyfoxx/dude-duck-backend:latest"
    container_name: worker
    command: celery -A src.services.tasks.service.celery worker --beat --loglevel=info
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis

  flower:
    image: "craazzzyyfoxx/dude-duck-backend:latest"
    container_name: flower
    command: celery --broker=${CELERY_BROKER_URL} flower --port=5555 --basic_auth=${POSTGRES_USER}:${POSTGRES_PASSWORD}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker


volumes:
    redis-data: