version: '3.8'

services :
  redis:
    image: redis:alpine
    restart: always
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT}
    ports:
      - "${PORT}:${PORT}"
  worker:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.services.tasks.service.celery worker --beat --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - redis
  flower:
    build: .
    command: celery --broker=${CELERY_BROKER_URL} flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker