version: '3.8'

services :
  redis:
    image: redis:alpine
    restart: always
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT}
    environment:
      - DEBUG=${DEBUG}
      - TELEGRAM_INTEGRATION=${TELEGRAM_INTEGRATION}
    ports:
      - "${PORT}:${PORT}"
  worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.services.tasks.service.celery worker --beat --loglevel=info
    volumes:
      - ./app:/app
    environment:
      - CELERY_SHEETS_SYNC_TIME=${CELERY_SHEETS_SYNC_TIME}
      - SYNC_BOOSTERS=${SYNC_BOOSTERS}
    depends_on:
      - redis
  flower:
    build: .
    command: celery --broker=${CELERY_BROKER_URL} flower --port=5555 --url_prefix=flower --basic_auth=${POSTGRES_USER}:${POSTGRES_PASSWORD}
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker
