version: '3.8'

services :
  redis:
    container_name: redis
    image: 'redis/redis-stack:latest'
    hostname: redis
    restart: unless-stopped
    environment:
      REDIS_ARGS: "--requirepass ${POSTGRES_PASSWORD}"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - backend

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT} --loop uvloop
    ports:
      - "${PORT}:${PORT}"
    networks:
      - npm
      - backend
  worker:
    container_name: worker
    command: celery -A src.services.tasks.service.celery worker --beat --loglevel=info
    depends_on:
      - redis
    networks:
      - backend
      - npm
  flower:
    container_name: flower
    command: celery --broker=${CELERY_BROKER_URL} flower --port=5555 --basic_auth=${POSTGRES_USER}:${POSTGRES_PASSWORD}
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker
    networks:
      - npm
      - backend


networks:
  backend:
    driver: bridge
  npm:
    external: true
    name: npm


volumes:
    redis-data: