version: '3.8'

services :
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT} --loop uvloop
    environment:
      - DEBUG=${DEBUG}
      - TELEGRAM_INTEGRATION=${TELEGRAM_INTEGRATION}
    ports:
      - "${PORT}:${PORT}"
  worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A src.services.tasks.service.celery worker --beat --loglevel=info
    volumes:
      - ./src:/src
    environment:
      - CELERY_SHEETS_SYNC_TIME=${CELERY_SHEETS_SYNC_TIME}
      - SYNC_BOOSTERS=${SYNC_BOOSTERS}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - POSTGRES_HOST=192.168.1.88
    depends_on:
      - redis
  flower:
    build: .
    command: celery --broker=${CELERY_BROKER_URL} flower --port=5555 --basic_auth=${POSTGRES_USER}:${POSTGRES_PASSWORD}
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker
