[tool.poetry]
name = "Dude Duck TG bot"
version = "2.1"
description = ""
authors = ["CraazzzyyFoxx <craazzzyyfoxx@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.23.0"
pydantic = {extras = ["email"], version = "^2.0.3"}
python-dotenv = "^1.0.0"
dateparser = "^1.1.7"
loguru = "^0.7.0"
sentry-sdk = {extras = ["fastapi"], version = "^1.28.1"}
fastapi = "^0.100.0"
uvloop = {version = "^0.17.0", platform="linux"}
gspread-asyncio = "^1.9.0"
google-api-python-client = "^2.94.0"
pydantic-extra-types = "^2.0.0"
phonenumbers = "^8.13.17"
beanie = "^1.20.0"
fastapi-users = {extras = ["beanie"], version = "^12.1.0"}
pydantic-settings = "^2.0.2"
httpx = "^0.24.1"
orjson = "^3.9.4"
apscheduler = {git = "https://github.com/agronholm/apscheduler.git"}
setuptools = "^68.0.0"
slowapi = "^0.1.8"
lru-cache = "^0.2.3"
deepdiff = "^6.3.1"
lru-dict = "^1.2.0"
locust = "^2.16.1"



[tool.aerich]
tortoise_orm = "config.tortoise"
location = "./migrations"
src_folder = "./."
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
