"""empty message

Revision ID: 6caae9e887ba
Revises: 
Create Date: 2023-10-26 17:35:38.174388

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '6caae9e887ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
